HelloWorld/force-app/main/default/objects/Application_Form__c/Application_Form__c.object-meta.xml
<CustomObject>
    <label>Application Form</label>
    <nameField>
        <displayFormat>AFID{000000}</displayFormat>
        <label>Application Form Name ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HelloWorld/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>SID-{000000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HelloWorld/force-app/main/default/objects/Student__c/fields/Application_Form__c.field-meta.xml
<CustomField>
    <fullName>Application_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Form</label>
    <referenceTo>Application_Form__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

HelloWorld/force-app/main/default/classes/formHelper1.cls
Public class formHelper1{

public static void preventRecordDeletion(List<Application_Form__c>formlist){

        Set<id>formIdSet = new Set<id>();
        // map to store , key as application_form id and value as student record.
        Map<id, Student__c>formidStudentRecMap = new Map<id, Student__c>(); // map of application form id and student record.
for(Application_Form__c fm : formlist){
formIdSet.add(fm.id);
        }
if(formIdSet != null &&formIdSet.size() > 0){
            List<Student__c>stdList = [select id, Application_Form__c from Student__c where Application_Form__c IN :formIdSet];
if(stdList.size() > 0){
for(Student__c std : stdList){
formidStudentRecMap.put(std.Application_Form__c, std); // for Map put() to add data into map
                }
            }

if(formidStudentRecMap != null &&formidStudentRecMap.values().size() > 0){
for(Application_Form__c fm : formlist){
if(formidStudentRecMap.containsKey(fm.id) && formidStudentRecMap.get(fm.id) != null){
 
                    }
                }
            }
        }
    }
}