HelloWorld/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APID-{000000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HelloWorld/force-app/main/default/objects/Applicant__c/fields/Police_verification__c.field-meta.xml
<CustomField>
    <fullName>Police_verification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Police verification</label>
    <type>Checkbox</type>
</CustomField>

HelloWorld/force-app/main/default/classes/newApplicantCustom_cx.cls
public with sharing class newApplicantCustom_cx {
  public Applicant__c objapp;
    public newApplicantCustom_cx(ApexPages.StandardController controller) {
     objapp= (Applicant__c) controller.getRecord();
    }
public void save(){

if(objapp.Gender__c=='Male' || objapp.Gender__c=='Female') {
 objapp.Police_verification__c=true;}
   else{
   objapp.Police_verification__c=false; }  
    insert objapp;
  ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM, 'Record created successfully...!!!!'));  
 
 } }